export * from './skill-angular-dialog.component';
export * from './skill-js-dialog.component';
export * from './skill-html-dialog.component';
export * from './skill-css-dialog.component';
export * from './skill-node-dialog.component';
export * from './skill-php-dialog.component';
export * from './skill-mysql-dialog.component';
export * from './skill-nginx-dialog.component';
export * from './dialogues.module';
